### PR TITLE
test(coverage): Separate unit and integration test coverage

### PR DESCRIPTION
**Pull request by grzesuav**

### CODE REVIEW

**Comment by grzesuav** [comment]
I believe slightly coverage decrease was caused by separation of unit and integration test reports

**Comment by AmitKumarDas** [comment]
Do you think we/tool can merge unit coverage and integration coverage

**Comment by grzesuav** [comment]
@AmitKumarDas it is merged, I mean in the report both are represented. this PR just mark them appropriately.

**Comment by grzesuav** [comment]
image
as you can see here, the overal coverage is 46%,  where 13% is unit, and 37% is integration

**Review by AmitKumarDas — APPROVED** [review]

**Pull request merged**
