### PR TITLE
Migrate GoogleCloudPlatform/metacontroller to metacontroller/metacontroller

### PR DESCRIPTION
**Pull request by alaimo**
Pull request to apply a full dump of [GoogleCloudPlatform/metacontroller](https://github.com/GoogleCloudPlatform/metacontroller/tree/master) to address the first part of [issue #6](https://github.com/metacontroller/metacontroller/issues/6).

### CODE REVIEW

**Comment by grzesuav** [comment]
I have strong objection against this method as we lost all information about commits and auhtors

**Comment by grzesuav** [comment]
it can be done like described in https://gist.github.com/niksumeiko/8972566 - I can test it. Especially I think that :
* git history must be kept
* all tags (releases) should also be moved
I can test the approach on my fork and let you know it it worked

**Comment by grzesuav** [comment]
I have tried this on https://github.com/grzesuav/metacontroller-moved , the number of commits, branches, releases and contributors are matching original one

**Comment by grzesuav** [comment]
Steps I did are : (as in https://gist.github.com/niksumeiko/8972566#gistcomment-1639106)
* `git clone --mirror git@github.com:GoogleCloudPlatform/metacontroller.git `
* `cd metacontroller.git`
* `git remote add new-origin git@github.com:grzesuav/metacontroller-moved.git`
 (change this to metacontroller/metacontroller)
* git push new-origin --mirror

**Comment by grzesuav** [comment]
there were a banch of error related to pushing some hidden refs, related to closed PR or so, but except log messages there is no charm

**Comment by alaimo** [comment]
Thanks @gresuav! I agree. I’ll run through your instructions and update the PR.

**Comment by AmitKumarDas** [comment]
Thanks @grzesuav it's my fault. I was always under the impression that author of source repo need to grant a GitHub permission to let this migration happen.

**Comment by alaimo** [comment]
@grzesuav thanks for pointing me in the right direction. This is now complete. The project has been mirrored and pushed to master with the full commit history. I merged a few pending dependabot PRs and opened a subsequent [PR](https://github.com/metacontroller/metacontroller/pull/12) to update the README.md

**Pull request closed without merging**
