### PR TITLE
chore(tests): Define api types and generate CRD from them

### PR DESCRIPTION
**Pull request by grzesuav**

### CODE REVIEW

**Comment by grzesuav** [comment]
need to debug this one, have some issues running the `catset` test afterwards

**Comment by grzesuav** [comment]
found the issue, it seems with current form, after applying `my-catset.yaml` object look like 
```yaml
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  serviceName: nginx-backend
  template:
    metadata: {}
    spec:
      containers:
      - image: gcr.io/google_containers/nginx-slim:0.8
        name: nginx
        ports:
        - containerPort: 80
          name: web
          protocol: TCP
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: www
      terminationGracePeriodSeconds: 1
      volumes:
      - downwardAPI:
          items:
          - fieldRef:
              fieldPath: metadata.name
            path: pod_name
        name: pod-info
  volumeClaimTemplates:
  - metadata: {}
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
```
where it should look like 
```yaml
spec:
  serviceName: nginx-backend
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        component: backend
    spec:
      volumes:
      - name: "pod-info"
        downwardAPI:
          items:
          - path: "pod_name"
            fieldRef:
              fieldPath: metadata.name
      terminationGracePeriodSeconds: 1
      containers:
      - name: nginx
        image: gcr.io/google_containers/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
      labels:
        app: nginx
        component: backend
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
```


so `metadata` is empty in attached templates for `Pod` and `VolumeClaim`

**Review by mikesmithgh — APPROVED** [review]

**Comment by grzesuav** [comment]
it seems 1.16 is having some compatbility issues, I will ditch it in favour of 1.24 before merging this one

**Pull request merged**
