### PR TITLE
refactor(#496): Extract and add abstraction around calling hooks

### PR DESCRIPTION
**Pull request by grzesuav**

### CODE REVIEW

**Review by mjsmith1028 — APPROVED** [review]
LGTM. Is the plan to eventually add a version field to https://github.com/grzesuav/metacontroller/blob/b0ed498bdbd06264a14315c743459ab44ca9f224/pkg/apis/metacontroller/v1alpha1/types.go#L118 ?

**Comment by grzesuav** [comment]
> LGTM. Is the plan to eventually add a version field to https://github.com/grzesuav/metacontroller/blob/b0ed498bdbd06264a14315c743459ab44ca9f224/pkg/apis/metacontroller/v1alpha1/types.go#L118 ?

Exactly, that and handling version selection in code, based on that field. Just didn't want to make too much changes in single PR

**Review by AmitKumarDas — APPROVED** [review]
/LGTM
Can we split the commit further so that things are simple to read & review?

**Comment by grzesuav** [comment]
> /LGTM Can we split the commit further so that things are simple to read & review?

Can try, however it was smallest sensible part. Sometimes is hard to do further split, especially when I am changing  typing/singatures etc ;)

**Pull request merged**
