### PR TITLE
fix(main): Fix waiting on signal before exiting

### PR DESCRIPTION
**Pull request by fpetkovski**
Fixes https://github.com/metacontroller/metacontroller/issues/289

### CODE REVIEW

**Comment by grzesuav** [comment]
thanks @fpetkovski for this ! As commit message will be used to trigger a release, can you adjust it to be understandable for people being out of context here ? 

Like :
```
fix(metrics): #289 - Wait on signal before exiting to fix http server with metrics
```


thanks !

**Review by grzesuav — CHANGES_REQUESTED** [review]
Please amend commit message

**Comment by fpetkovski** [comment]
Sure thing, the commit message should be changed now

**Review by grzesuav — APPROVED** [review]

**Pull request merged**
