### PR TITLE
chore(examples): Update "Create a Controller" to use python3

### PR DESCRIPTION
**Pull request by sathieu**
Python2 is gone now!

### CODE REVIEW

**Comment by grzesuav** [comment]
@sathieu thanks for PR, can you :
* change commit and PR title to have `chore(examples` prefix
* add signoff (to satisfy DCO check)  - instructions are there

**Comment by sathieu** [comment]
Thanks @grzesuav Back to you.

Please note that python2 is used in other places:

```
$ git grep python:2
examples/clusteredparent/manifest/cluster-parent.yaml:        image: python:2.7
examples/crd-roles/manifest/crd-role-controller.yaml:        image: python:2.7
examples/daemonjob/manifest/daemonjob-controller.yaml:        image: python:2.7
examples/indexedjob/manifest/indexedjob-controller.yaml:        image: python:2.7
```

**Comment by grzesuav** [comment]
> Please note that python2 is used in other places:
> 

Yes, I am aware ;) but other PR's in place know, will get back to this once I get time, also we are open for contributions :)

**Review by grzesuav — APPROVED** [review]

**Pull request merged**
