### PR TITLE
chore(tests): #16 - Add testing pipeline to github actions

### PR DESCRIPTION
**Pull request by grzesuav**

### CODE REVIEW

**Comment by grzesuav** [comment]
need to work bit on this due to slightly different paths after check-out repository - https://github.com/grzesuav/metacontroller/runs/713561233?check_suite_focus=true

**Comment by grzesuav** [comment]
```
can't load package: package ./apis/metacontroller/v1alpha1: code in directory /home/runner/work/metacontroller/metacontroller/apis/metacontroller/v1alpha1 expects import "metacontroller.app/apis/metacontroller/v1alpha1"
can't load package: package _/home/runner/work/metacontroller/metacontroller: cannot find package "_/home/runner/work/metacontroller/metacontroller" in any of:
	/opt/hostedtoolcache/go/1.13.5/x64/src/_/home/runner/work/metacontroller/metacontroller (from $GOROOT)
	/home/runner/go/src/_/home/runner/work/metacontroller/metacontroller (from $GOPATH)
```

**Comment by grzesuav** [comment]
@AmitKumarDas maybe you can point me to right direction what is going on here?

**Comment by AmitKumarDas** [comment]
@grzesuav you may try to run this in a folder named `metacontroller.app`.

**Comment by grzesuav** [comment]
need to adjust it a bit, I want to do replace travis.yml job, seems I need to adjust GOPATH, will try to work on it today

**Comment by grzesuav** [comment]
@AmitKumarDas I did test setup (results - https://github.com/grzesuav/metacontroller/actions/runs/120590887 )

it seems test are executed, but hmm it seems that there is actually very few test classes. Or I miss something ?

**Comment by AmitKumarDas** [comment]
@grzesuav I will take a look. Yes original metacontroller has little to no tests. It relies more on examples. I agree this is not a great thing.

**Pull request merged**
