### PR TITLE
Support cluster level "related" resources as well as resources from other namespaces

### LINKED ISSUE #345: Allow cluster-scoped related resources for namespaced parents
Given an `Ingress` as parent (namespaced), I want to get access to it's parent `IngressClass` (cluster-scoped).

Some context [here](https://gitlab.com/kubitus-project/kubitus-ingress-operator/-/blob/902ca26cbf045d0367f6239c1461786f8746fc0a/kubitus_ingress_operator/ingress2istio.py#L44-52) and [here](https://gitlab.com/kubitus-project/kubitus-ingress-operator/-/blob/902ca26cbf045d0367f6239c1461786f8746fc0a/kubitus_ingress_operator/ingress2istio.py#L90-107).

### PR DESCRIPTION
**Pull request by splitice**
Merged to bring up to date with master and apply cleanly

Fixes #345 (and others)

### CODE REVIEW

**Comment by splitice** [comment]
The last failing test, I'm not sure it should pass.

Anyway this allows cluster resources to be used as additional related resources. Uses `*` namespace as a wildcard (user is expected to understand the implications and do any manual filtering)

**Comment by grzesuav** [comment]
hi @splitice , thank for PR, however introducing support for cluster level resources requires introducing an API versioning scheme, which is not done yet.

**Comment by hassenius** [comment]
I'm interested in this one too, as I also have a use case for cluster scoped relatedResources.
In my case I have namespace scoped parents and children, but include info from a related cluster scoped resource

**Comment by grzesuav** [comment]
Closing, https://github.com/metacontroller/metacontroller/issues/496 need to be implemented first, later on work on https://github.com/metacontroller/metacontroller/issues/345

**Pull request closed without merging**
