### PR TITLE
chore(examples): Refactor examples to use kustomize

### PR DESCRIPTION
**Pull request by grzesuav**
Changes: 
* use kustomize - it makes creation of configmap easier, and open a way to provide examples compatibile with both `v1` and `v1beta1` crd version
* update readmes
* update test scripts
* add to test scripts option to run with CRD's in version `v1` and `v1beta`
* add kubernetes 13/14/15 tests

### CODE REVIEW

**Review by AmitKumarDas — APPROVED** [review]
This is great @grzesuav 
Do we have enough information on installing Kustomize (exact version etc) as part of the README? This will help the contributors to run these tests or create new ones on their setups.

**Comment by grzesuav** [comment]
> This is great @grzesuav
> Do we have enough information on installing Kustomize (exact version etc) as part of the README? This will help the contributors to run these tests or create new ones on their setups.

hi @AmitKumarDas , acutally since few versions `kustomize` is included into `kubectl` (you use it as `kubectl apply -k ...) since `kubectl 1.14` (https://www.jetstack.io/blog/kustomize-cert-manager/ , https://github.com/kubernetes/enhancements/issues/633 ) so nothing more than `kubectl` is needed

**Comment by grzesuav** [comment]
I can add more info to `contributors.md` in next PR (do not want to make this one even bigger)

**Review by AmitKumarDas — APPROVED** [review]

**Pull request merged**
