### PR TITLE
fix: [#650] - Added 'mountPath' as possible merge-key to avoid that 'name' is treated as unique value for volumeMounts

### PR DESCRIPTION
**Pull request by EmielBruijntjes**
In issue #650 we ran into the problem that volumeMounts were not correctly merged. This happens when you have multiple volumeMounts that all refer to the same volume, but using different mountPaths. The reason for this seems to come from the merging-algorithm in the meta-controller, which is a bit fuzzy and incorrectly assumes that 'name' always has a unique value (which is not the case here, because 'name' refers to the volume and the same volume can be used for multiple volumeMounts).

In this pull-request we added an "mountPath" option as extra option to the list of possible mergeKeys. This fixes the issue for us, and I think it is reasonably safe to assume that the mountPath property is normally unique.

### CODE REVIEW

**Comment by EmielBruijntjes** [comment]
Hmmmm, so difficult to get through the github merge process. It is only one line that was added to the code, do I really have to study to find out how this "codecov" robot and "signed-off-by" process works? I would be just as happy if this PR was rejected and that someone else who *does* know the rules and procedures of this repo would add this extra line, or tell me why our fix was wrong.

Is there anything that I can do to speed up the process? Maybe @grzesuav? It would be really nice if you can pick it up from here, and/or give some feedback.

**Comment by grzesuav** [comment]
@EmielBruijntjes when you click `details` on DCO it tell you what to do

**Comment by grzesuav** [comment]
also ,please squash the commits to single one, with `fix(#650) : Add 'mountPath' as merge key` as we use semantic commits

**Comment by EmielBruijntjes** [comment]
Could you be so kind to help me out with this? I am not so experienced with git. I only know 'git commit' and 'git push' (sorry about that). If this was a 500 line change I would be more than happy to do all the studying, write unit tests and so on, but could you just take a look at our 1-line change and give feedback like "no, this stinks" or "yes, this is helpful" -- I prefer to fail fast here.

**Comment by grzesuav** [comment]
if it helps then I am for it, ultimate solution for all the issues with merging will be switching to SSA, I can create separate PR with that if you are not advanced with git

**Comment by grzesuav** [comment]
https://github.com/metacontroller/metacontroller/pull/663

**Comment by EmielBruijntjes** [comment]
Great, awesome! I close this one then.

**Pull request closed without merging**
